### ISSUE TITLE
Bug: Rule prefer-in-document expects the argument to `expect` to be `CallExpression`

### ISSUE THREAD

**Issue by AntonNiklasson** [testing-library/eslint-plugin-jest-dom#104]
- `eslint-plugin-jest-dom` version: `3.3.0`
- `node` version: `12.19.0`
- `npm` version: `6.14.8`

## Relevant code or config

```javascript
const element = await screen.findByText('lorem ipsum');
expect(element).toBeDefined()
```

## What happened:

```
Oops! Something went wrong! :(

ESLint: 7.8.0

TypeError: Cannot read property 'name' of undefined
Occurred while linting /Users/anton/code/milkywire/enterprise/components/page-specific/impacter-tools/create/CreatePosts.spec.tsx:213
    at check (/Users/anton/code/milkywire/enterprise/node_modules/eslint-plugin-jest-dom/dist/rules/prefer-in-document.js:39:27)
    at CallExpression[callee.object.callee.name='expect'][callee.property.name=/(toHaveLength|toBeDefined|toBeNull)/] (/Users/anton/code/milkywire/enterprise/node_modules/eslint-plugin-jest-dom/dist/rules/prefer-in-document.js:97:7)
    at /Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/anton/code/milkywire/enterprise/node_modules/eslint/lib/linter/linter.js:952:32
```

## Suggested solution

I'll PR a fix for this shortly.

**Comment by AntonNiklasson** [comment]
This adds a bit more complexity. Perhaps we should only lint on what we are sure to be the return value from a TL query? What about this case: 

```
const user = getUser();
expect(user).toBeNull();
```

You probably don't want that fixed to `expect(user).not.toBeInTheDocument();`

Should we stick do linting on queries run within the `expect`? Or should this be extended to check any variables passed to `expect`?

**Comment by benmonro** [comment]
Yes. We should only report on queries or variables we know come from them
